name: 'Download File from GCP Bucket'
description: 'Downloads a file from a Google Cloud Storage bucket'
inputs:
  bucket_name:
    description: 'GCP bucket name'
    required: true
  target_file:
    description: 'Use this input if you want to download a specific file from the bucket'
    required: false
  target_folder:
    description: 'Use this input if you want to download all files from a specific folder in the bucket'
    required: false
  local_download_path:
    description: 'Path where the downloaded file will be saved'
    required: true

runs:
  using: node20
  main: dist/index.js
