name: 'Download File from GCP Bucket'
description: 'Downloads a file from a Google Cloud Storage bucket'
inputs:
  bucket_name:
    description: 'GCP bucket name'
    required: true
  target_file_name:
    description: 'Name of the file to download'
    required: true
  local_download_path:
    description: 'Path where the downloaded file will be saved'
    required: true

runs:
  using: node20
  main: dist/index.js
